<a href="https://colab.research.google.com/github/acsnuisa/LinAlg-2021/blob/main/Assignment6_NUISA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for ECE
## Laboratory 6 : Matrix Operations

Now that you have a fundamental knowledge about representing and operating with vectors as well as the fundamentals of matrices, we'll try to the same operations with matrices and even more.

### Objectives
At the end of this activity you will be able to:
1. Be familiar with the fundamental matrix operations.
2. Apply the operations to solve intermediate equations.
3. Apply matrix algebra in engineering solutions.

## Discussion

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## Transposition

One of the fundamental operations in matrix algebra is Transposition. "Flipping" a matrix over its diagonal leads to its Transposition. The rows and columns get swapped. The symbol is a "T" placed above and to the right like this: $A^T$. Therefore for a matrix $A$ its transpose is denoted as $A^T$ [1]. For example:


$$A = \begin{bmatrix} 1 & 2 & 5\\5 & -1 &0 \\ 0 & -3 & 3\end{bmatrix} $$

$$ A^T = \begin{bmatrix} 1 & 5 & 0\\2 & -1 &-3 \\ 5 & 0 & 3\end{bmatrix}$$

As seen above, it is a simple operation in which we utilize its interchange of elements. Thus Transpose of a Matrix is defined as “A Matrix which is formed by turning all the rows of a given matrix into columns and vice-versa.” [2]

This can now be achieved programmatically by using `np.transpose()` or using the `T` method.

## Dot Product / Inner Product

These basic operations are the building blocks of complex machine learning and deep learning models hence it is valuable to have a comprehensive understanding of this. The dot product of two vectors is the sum of the products of elements with regards to position. The first element of the first vector is multiplied by the first element of the second vector and so on [3].

If you recall the dot product from laboratory activity before, we will try to implement the same operation with matrices. In matrix dot product we are going to get the sum of products of the vectors by row-column pairs. So if we have two matrices $X$ and $Y$:

$$X = \begin{bmatrix}x_{(0,0)}&x_{(0,1)}\\ x_{(1,0)}&x_{(1,1)}\end{bmatrix}, Y = \begin{bmatrix}y_{(0,0)}&y_{(0,1)}\\ y_{(1,0)}&y_{(1,1)}\end{bmatrix}$$

The dot product will then be computed as:
$$X \cdot Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} & x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} & x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}
\end{bmatrix}$$

So if we assign values to $X$ and $Y$:
$$X = \begin{bmatrix}1&2\\ 0&1\end{bmatrix}, Y = \begin{bmatrix}-1&0\\ 2&2\end{bmatrix}$$

$$X \cdot Y= \begin{bmatrix} 1*-1 + 2*2 & 1*0 + 2*2 \\  0*-1 + 1*2 & 0*0 + 1*2 \end{bmatrix} = \begin{bmatrix} 3 & 4 \\2 & 2 \end{bmatrix}$$
This could be achieved programmatically using `np.dot()`, `np.matmul()` or the `@` operator.

In matrix dot products there are additional rules compared with vector dot products. Since vector dot products were just in one dimension there are less restrictions. Since now we are dealing with Rank 2 vectors we need to consider some rules:

### Rule 1: The inner dimensions of the two matrices in question must be the same. 

So given a matrix $A$ with a shape of $(a,b)$ where $a$ and $b$ are any integers. If we want to do a dot product between $A$ and another matrix $B$, then matrix $B$ should have a shape of $(b,c)$ where $b$ and $c$ are any integers. So for given the following matrices:

$$A = \begin{bmatrix}2&4\\5&-2\\0&1\end{bmatrix}, B = \begin{bmatrix}1&1\\3&3\\-1&-2\end{bmatrix}, C = \begin{bmatrix}0&1&1\\1&1&2\end{bmatrix}$$

So in this case $A$ has a shape of $(3,2)$, $B$ has a shape of $(3,2)$ and $C$ has a shape of $(2,3)$. So the only matrix pairs that is eligible to perform dot product is matrices $A \cdot C$, or $B \cdot C$.  

### Rule 2: Dot Product has special properties

Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:
 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$ 

## Determinant

Determinants are considered as a scaling factor of matrices. They can be considered as functions of stretching out and the shrinking in of the matrices. Determinants take a square matrix as the input and return a single number as its output. A square matrix can be defined as a matrix that has an equal number of rows and columns [4].

The determinant of some matrix $A$ is denoted as $det(A)$ or $|A|$. So let's say $A$ is represented as:
$$A = \begin{bmatrix}a_{(0,0)}&a_{(0,1)}\\a_{(1,0)}&a_{(1,1)}\end{bmatrix}$$
We can compute for the determinant as:
$$|A| = a_{(0,0)}*a_{(1,1)} - a_{(1,0)}*a_{(0,1)}$$
So if we have $A$ as:
$$A = \begin{bmatrix}1&4\\0&3\end{bmatrix}, |A| = 3$$

But you might wonder how about square matrices beyond the shape $(2,2)$? We can approach this problem by using several methods such as co-factor expansion and the minors method. This can be taught in the lecture of the laboratory but we can achieve the strenuous computation of high-dimensional matrices programmatically using Python. We can achieve this by using `np.linalg.det()`.

## Inverse

We can find the matrix inverse only for square matrices, whose number of rows and columns are equal such as 2 × 2, 3 × 3, etc. In simple words, inverse matrix is obtained by dividing the adjugate of the given matrix by the determinant of the given matrix [5]. The inverse of a matrix is another fundamental operation in matrix algebra. Determining the inverse of a matrix let us determine if its solvability and its characteristic as a system of linear equation. Another use of the inverse matrix is solving the problem of divisibility between matrices. Although element-wise division exists but dividing the entire concept of matrices does not exists. Inverse matrices provides a related operation that could have the same concept of "dividing" matrices.

Now to determine the inverse of a matrix we need to perform several steps. So let's say we have a matrix $M$:
$$M = \begin{bmatrix}1&7\\-3&5\end{bmatrix}$$
First, we need to get the determinant of $M$.
$$|M| = (1)(5)-(-3)(7) = 26$$
Next, we need to reform the matrix into the inverse form:
$$M^{-1} = \frac{1}{|M|} \begin{bmatrix} m_{(1,1)} & -m_{(0,1)} \\ -m_{(1,0)} & m_{(0,0)}\end{bmatrix}$$
So that will be:
$$M^{-1} = \frac{1}{26} \begin{bmatrix} 5 & -7 \\ 3 & 1\end{bmatrix} = \begin{bmatrix} \frac{5}{26} & \frac{-7}{26} \\ \frac{3}{26} & \frac{1}{26}\end{bmatrix}$$
For higher-dimension matrices you might need to use co-factors, minors, adjugates, and other reduction techinques. To solve this programmatially we can use `np.linalg.inv()`.

To validate the wether if the matric that you have solved is really the inverse, we follow this dot product property for a matrix $M$:
$$M\cdot M^{-1} = I$$

## Activity

### Task 1

Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$.
In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [ ]:
#import

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
## Matrix Declarations

In [2]:
A = np.array([
         [4,2,0],
         [0,6,9],
         [3,7,2]     
])
B = np.array([
         [1,2,3],
         [9,7,8],
         [6,9,0]     
])
C = np.array([
         [7,2,1],
         [4,7,8],
         [3,6,0]
])

#### $A \cdot B \neq B \cdot A$

In [3]:
np.dot(A,B)

array([[ 22,  22,  28],
       [108, 123,  48],
       [ 78,  73,  65]])

In [4]:
np.dot(B,A)

array([[ 13,  35,  24],
       [ 60, 116,  79],
       [ 24,  66,  81]])

#### $A \cdot (B \cdot C) = (A \cdot B) \cdot C$

In [ ]:
X = np.dot(B,C)
Y = np.dot(A,B)
Q = np.dot(A,X)
W = np.dot(Y,C)

In [ ]:
print(Q)

[[ 326  366  198]
 [1392 1365 1092]
 [1033 1057  662]]


In [ ]:
print(W)

[[ 326  366  198]
 [1392 1365 1092]
 [1033 1057  662]]


#### $A\cdot(B+C) = A\cdot B + A\cdot C$

In [ ]:
E = B + C
print(E)

[[ 8  4  4]
 [13 14 16]
 [ 9 15  0]]


In [ ]:
np.dot(A,E)

array([[ 58,  44,  48],
       [159, 219,  96],
       [133, 140, 124]])

In [ ]:
O = np.dot(A,B)
print(O)

[[ 22  22  28]
 [108 123  48]
 [ 78  73  65]]


In [ ]:
P = np.dot(A,C)
print(P)

[[36 22 20]
 [51 96 48]
 [55 67 59]]


In [ ]:
O + P

array([[ 58,  44,  48],
       [159, 219,  96],
       [133, 140, 124]])

#### $(B+C)\cdot A = B\cdot A + C\cdot A$

In [ ]:
np.dot((B+C),A)

array([[ 44,  68,  44],
       [100, 222, 158],
       [ 36, 108, 135]])

In [ ]:
N = np.dot(B,A)
M = np.dot(C,A)

In [ ]:
N+M

array([[ 44,  68,  44],
       [100, 222, 158],
       [ 36, 108, 135]])

#### $A\cdot I = A$

In [ ]:
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
print(A)

[[4 2 0]
 [0 6 9]
 [3 7 2]]


In [ ]:
np.dot(A,I)

array([[4., 2., 0.],
       [0., 6., 9.],
       [3., 7., 2.]])

#### $A\cdot \emptyset = \emptyset$

In [ ]:
z_mat = np.zeros(A.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a_dot_z = A.dot(np.zeros(A.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.array_equal(a_dot_z,z_mat)

True

In [ ]:
null_mat = np.empty(A.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

## Conclusion

Compared to the last experiment, we are provided with more functions and operations regarding matrices. This experiment delved on the further emphasizing more of Colabs greater functions like Transposition, Dot Product, Determinants and Inverse Matrices. Comparing Python's computation with manual solving, we can conclude that it is indeed accurate and proper. With Python being the faster way to compute, depending on the complexity of the problem. An example of this is the Inverse of Matrices, where Python greatly solves with ease compared to when we solve it manually. Another example is Transposition and Determinants. Since Transposition can be done without computing we do not need to rely on Colab as much as we relied on it during Inverse of Matrices. Determinants can also be done through different techniques as well as through the use of a calculator. Hence, we don't need to rely that much on colab albeit still depending on the comlexity at hand. Furthermore, Dot Product/Inner Product as simple as it sounds can be complicated if the matrix has more than 1 row. Since Dot Product is the sum of each product of x,y,z or i,j,k  respectively. Solving a 1 by 3 matrix can be easy as using "eyeing" it but if the dimensions will become larger it would prove to be more complex depending on the given values. That is where the standard properties of Dot Product in some cases will not be applied. Therefore, what is to be applied now is its Special Properties as what was given in the Task above. The given Special Properties above were to be proven through Colab with one property being "unequal". This is the change in standard properties regarding the Dot Product, in which we can delve deeper in the reference below [3] In conclusion, Python can also be used to solve complex problems such as Element Wise Multiplication and the Dot Product, with the right commands and functions we can utilize this language to different applications.

References:

[1] MathisFun(n.d)"MathisFun", Definition of Transpose (matrix). Available: https://www.mathsisfun.com/definitions/transpose-matrix-.html. [Accessed: Oct. 24, 2021].

[2] Byju's(n.d)"Byju's", Transpose of a Matrix. Available: https://byjus.com/maths/transpose-of-a-matrix/. [Accessed: Oct. 24, 2021].

[3] Soner Yıldırım(June 20, 2020)"towards data science", Linear Algebra Basics: Dot Product and Matrix Multiplication. Available: https://towardsdatascience.com/linear-algebra-basics-dot-product-and-matrix-multiplication-2a7624942810#:~:text=Dot%20products%20are%20done%20between,to%20the%20number%20of%20columns. [Accessed: Oct. 24,2021]

[4] Cuemath(n.d)"Cuemath",Determinants. Available: https://www.cuemath.com/algebra/determinants/. [Accessed: Oct. 24,2021]

[5] Byju's(n.d)"Byju's", Inverse Matrix. Available: https://byjus.com/maths/inverse-matrix/. [Accessed: Oct. 24, 2021].