<a href="https://colab.research.google.com/github/acsnuisa/LinAlg-2021/blob/main/Assignment4_NUISA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for ECE
## Laboratory 4 : Matrices
![image](https://drive.google.com/uc?export=view&id=1xJLUKtpiXA1nezyfhoSLOtdcqgZn4JnX)

[1] Introduction to Matrices

Now that you have a fundamental knowledge about Python, we'll try to look into greater dimensions.

### Objectives
At the end of this activity you will be able to:
1. Be familiar with matrices and their relation to linear equations.
2. Perform basic matrix operations.
3. Program and translate matrix equations and operations using Python.

## Introduction to Matrices

> A matrix is a two-dimensional array of numbers with rows and columns arranged in rows and columns. Matrices are a type of matrix that can be used to organize, store, and manipulate mathematical data. In the actual world, matrices have a wide range of applications and uses. Matrices are useful when working with models that are based on systems of linear equations [1].
>> For example, matrix *A* has two rows and three columns.

$$
A=\begin{bmatrix} -2 & 5 & 6\\ 5 & 2 & 7\end{bmatrix} \\
$$
$$
B=\begin{bmatrix} -8 & -4 \\ 23 & 12\\ 18 & 10\end{bmatrix}
$$

> * In contrast, matrix *B* has three rows and two columns, so it is a 3 x 2 matrix. \
Keep in mind that: Rows x Columns!



### Matrix Dimensions



> Khan Academy provided a general introduction into matrices so we can further understand its concept. The dimensions of a matrix tells its size: the number of rows and columns of the matrix, in that order. Since matrix *A* has two rows and three columns, we write its dimensions as 2 x 3, pronounced "two by three" [2].

$$
A=\begin{bmatrix} -2 & 5 & 6\\ 5 & 2 & 7\end{bmatrix} \\
$$

#### Representing a linear system with matrices

>  Matrices can be used to solve systems of equations. However, we must learn how to represent systems with matrices [3]. First and foremost, the equation must be arranged properly in the standard form. Then we take its constants and put it into its matrix form from left to right (including the constant on the right side)

Let's say for example you have $A$ and $B$ as system of equation.

$$
A = \left\{
    \begin{array}\
        -2x + 5y + 6z \\ 
        5x + 2y +7z
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        -8x - 4y\\ 
        23x + 12y \\
        18x + 10y 
    \end{array}
\right. $$

We could see that $A$ is a system of 2 equations with 3 parameters. While $B$ is a system of 3 equations with 2 parameters. We can represent them as matrices by:

$$
A=\begin{bmatrix} -2 & 5 & 6\\ 5 & 2 & 7\end{bmatrix} \\
B=\begin{bmatrix} -8 & -4 \\ 23 & 12\\ 18 & 10\end{bmatrix}
$$

### Declaring Matrices

> The entities or numbers in matrices are called the elements of a matrix. These elements are arranged and ordered in rows and columns which form the list/array-like structure of matrices. And just like arrays, these elements are indexed according to their position with respect to their rows and columns. This can be reprsented just like the equation below. Whereas  A  is a matrix consisting of elements denoted by  ai,j . Denoted by  i  is the number of rows in the matrix while  j  stands for the number of columns.
Do note that the  size  of a matrix is  i×j .

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$

> There are several ways of classifying matrices. Once could be according to their <b>shape</b> and another is according to their <b>element values</b>. We'll try to go through them.

## Activity

### Task 1

Create a function named `desc_mat()` that througouhly describes a matrix, it should: <br>
1. Displays the shape, size, and rank of the matrix. <br>
2. Displays whether the matrix is square or non-square. <br>
3. Displays whether the matrix is an empty matrix. <br>
4. Displays if the matrix is an identity, ones, or zeros matrix <br>
   
Use sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [ ]:
## Function area

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

In [3]:
def desc_mat(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')

In [ ]:
## Matrix declarations

In [328]:
T= np.array([
    [1,2,3],
    [4,5,5],
    [8,7,9]
])
E= np.array([
    [8,9,7],
    [6,5,4],
    [1,2,3]
])

A = np.array([])

S = np.eye(69)

E = np.ones((6,9))

R = np.zeros((3,3))

In [ ]:
## Test Areas

In [329]:
desc_mat(T)

Matrix:
[[1 2 3]
 [4 5 5]
 [8 7 9]]

Shape:	(3, 3)
Rank:	2
Is Square: True



In [330]:
desc_mat(E)

Matrix:
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]

Shape:	(6, 9)
Rank:	2
Is Square: False



In [331]:
desc_mat(A)

Matrix is Null


In [332]:
desc_mat(S)

Matrix:
[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]

Shape:	(69, 69)
Rank:	2
Is Square: True



In [333]:
desc_mat(E)

Matrix:
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]

Shape:	(6, 9)
Rank:	2
Is Square: False



In [334]:
desc_mat(R)

Matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Shape:	(3, 3)
Rank:	2
Is Square: True



### Task 2

Create a function named `mat_operations()` that takes in two matrices a input parameters it should:<br>
 1. Determines if the matrices are viable for operation and returns your own error message if they are not viable.
 2. Returns the sum of the matrices.
 3. Returns the difference of the matrices.
 4. Returns the element-wise multiplication of the matrices.
 5. Returns the element-wise division of the matrices.

Use at least sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [ ]:
## Function area

In [36]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

In [339]:
def mat_operations(matrix):
    if matrix.size > 0:
        is_viable = True if matrix.shape [0] == matrix.shape[1] else False
        print(f'Matrix\n{matrix}\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Viable: {is_viable}')
    else:
        print('Use Element Wise Operation')

In [69]:
## Matrix declarations

In [340]:
T= np.array([
    [1,2,3],
    [4,5,5],
    [8,7,9]
])
E= np.array([
    [8,9,7],
    [6,5,4],
    [1,2,3]
])

In [306]:
## Test Areas

In [341]:
mat_operations(T+E)

Matrix
[[ 9 11 10]
 [10 10  9]
 [ 9  9 12]]
Shape:	(3, 3)
Rank:	2
Is Viable: True


In [342]:
mat_operations(T-E)

Matrix
[[-7 -7 -4]
 [-2  0  1]
 [ 7  5  6]]
Shape:	(3, 3)
Rank:	2
Is Viable: True


In [343]:
mat_operations(T*E)

Matrix
[[ 8 18 21]
 [24 25 20]
 [ 8 14 27]]
Shape:	(3, 3)
Rank:	2
Is Viable: True


In [344]:
mat_operations(T/E)

Matrix
[[0.125      0.22222222 0.42857143]
 [0.66666667 1.         1.25      ]
 [8.         3.5        3.        ]]
Shape:	(3, 3)
Rank:	2
Is Viable: True


In [345]:
alpha=10**-10
mat_operations(T/(alpha+E))

Matrix
[[0.125      0.22222222 0.42857143]
 [0.66666667 1.         1.25      ]
 [8.         3.5        3.        ]]
Shape:	(3, 3)
Rank:	2
Is Viable: True


## Conclusion

> When high-speed computers with hierarchical memory (based on multiple levels 
of caches) are utilized to tackle huge computational workloads, efficient matrix computation organization becomes increasingly crucial. Matrix computations are used in the treatment of nearly all large-scale models [4].These jumble of numbers in the matrix format stems from systems of equations. Matrices are commonly seen in mathematics, but we've never actually seen how it is applied. Since matrices are a type of matrix that can be used to organize, store, and manipulate mathematical data. Hence, we can utilize this depending on its real world applications. Real world applications of matrices include encryption, games, economics and business, Physics, and Geology. In encryption, Matrices are used  to scramble data for security reasons. They are used to encode and decode data. There is a key that aids in the encoding and decoding of data generated by matrices. Furthermore, games utilize matrices to modify the thing in three-dimensional space. They convert it from a three-dimensional matrix to a two-dimensional matrix as needed. In economics and business, it is used to research a company's trends, shares, and other factors. To develop business models, for example. In Physics there are different applications for Matrices. Electrical circuits, Quantum physics, and Optics are all studied using matrices. It aids in the estimation of battery power outputs and the conversion of electrical energy into another useable form through resistors. As a result, matrices play a significant part in calculations. Especially when applying Kirchoff's voltage and current rules to solve difficulties. It aids in the study and application of quantum physics. Lastly, in Geology it is generally used for seismic surveys [5]. These are few of the applications of Matrices, and it can solve various problems on different fields. Matrices solve problems in technology through it's first application which is encryption. In which it is used to scramble data for security purposes. It is also a way of providing quick approximations of more complicated calculations.

## References
[1]Rupinder Sekhon and Roberta Bloom(Sep 5, 2021)"Math LibreTexts", Introduction to Matrices. Available: https://math.libretexts.org/Bookshelves/Applied_Mathematics/Applied_Finite_Mathematics_(Sekhon_and_Bloom)/02%3A_Matrices/2.01%3A_Introduction_to_Matrices. [Accessed: Sept. 22, 2021].

[2]"Khan Academy",Intro to matrices(n.d). Avaiable: https://www.khanacademy.org/math/precalculus/x9e81a4f98389efdf:matrices/x9e81a4f98389efdf:mat-intro/a/intro-to-matrices. [Accessed: Sept. 22, 2021].

[3]“Representing linear systems with matrices,”(n.d). Available: https://www.khanacademy.org/math/algebra-home/alg-matrices/alg-representing-systems-with-matrices/a/representing-systems-with-matrices. Available: http://www.vmsk.org/Layman.pdf. [Accessed: Sept. 22, 2021].

[4]Giorgio Semenza(2006)"Studies in Computational Mathematics",Applicability to other models. Avilable: https://www.sciencedirect.com/bookseries/studies-in-computational-mathematics. [Accessed: Sept. 23, 2021].

[5]Livia Ferrao(May 20, 2021)"Embibe", Where Are Matrices Used In Daily Life? Read Here To Know. Available: https://www.embibe.com/exams/where-are-matrices-used-in-daily-life/. [Accessed: Sept. 23,2021].